name: CI
on:
  push:
    branches:
      - "*"
      - "**"
      - "!main"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Electron Rebuild Dependencies
        run: npm run rebuild
      - name: Build
        run: npm run build
