name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Electron Rebuild Dependencies
        run: npm run rebuild
      - name: Build
        run: npm run build
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
      - name: Publish app
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
      - uses: actions/upload-artifact@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          name: remix-electron-llamafile-${{ steps.release.outputs.tag_name }}-${{ matrix.os }}
          path: out/make
