name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Electron Rebuild Dependencies
        run: npm run rebuild
      - name: Build
        run: npm run build
      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
      - uses: actions/upload-artifact@v4
        with:
          name: remix-electron-llamafile-${{ matrix.os }}-v${{needs.check-version.outputs.VERSION}}
          path: out/make
          overwrite: true
